#!/bin/sh -e

NAME=fah-node
_ETC=/etc/$NAME
_HOME=/var/lib/$NAME
_LOG=/var/log/$NAME

case "$1" in
  remove)
    systemctl daemon-reload || true
    ;;

  purge)
    # Remove all files
    rm -rf $_ETC $_HOME $_LOG

    # Remove user and group
    deluser  --quiet $NAME || true
    delgroup --quiet $NAME || true
    ;;
esac
