#!/bin/bash -e

NAME=fah-node
_ETC=/etc/$NAME
_HOME=/var/lib/$NAME
_LOG=/var/log/$NAME
_SHARE=/usr/share/$NAME
CONFIG=$_ETC/config.xml

# Create config directories
install -d -m 775 -o $NAME -g $NAME $_ETC $_HOME $_HOME/logs

# Create config
if [ ! -e $CONFIG ]; then
  echo "Creating '$CONFIG'."

  # Discover public IP
  IP=$(curl -s https://api.ipify.org)

  # Discover domain name
  DOMAIN=
  if [ "$IP" != "" ]; then
    if [ -x /usr/bin/dig ]; then
      DOMAIN=$(/usr/bin/dig +short -x $IP)
    else
      DOMAIN=$(domainname -f $IP)
    fi

    if [[ $DOMAIN != *.* ]]; then
      DOMAIN=
    fi
  fi

  sed "s/EXTERNAL_IP/$IP/;s/DOMAINS/$DOMAIN/" \
      < $_SHARE/sample-config.xml > $CONFIG
  chmod 664 $CONFIG
fi

# Link log files
if [ ! -e $_LOG ]; then
  ln -fs $_HOME/logs $_LOG
fi
if [ ! -e $_LOG/log.txt ]; then
  ln -fs $_HOME/log.txt $_LOG/
fi

systemctl daemon-reload || true

# Add/update state file, required for purge action in postrm
deb-systemd-helper update-state $NAME.service || true

# Only enable/start on initial install
if [ -z "$2" ]; then
  systemctl -q enable $NAME || true
  systemctl start $NAME || true
else
  # Upgrade
  # Reenable if fixing broken symlink
  if dpkg --compare-versions "$2" lt 0.0.3; then
    systemctl -q enable $NAME || true
  fi

  systemctl restart $NAME || true
fi

echo
echo "Next open and redirect ports by running."
echo
echo "    sudo fah-node-ports"
echo
echo "Install ``iptables-persistent`` to make firewall changes persist:"
echo
echo "    sudo apt-get install -y iptables-persistent"
echo
echo "Answer yes to saving current ipv4 rules."
echo
